name: 'amplitude_source'
version: '0.1.0'
config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  amplitude_source:
    +schema: stg_amplitude
    materialized: table

#  look at mixpanel
vars:
  amplitude_source:
    event: "{{ source('amplitude', 'event') }}"
    event_type: "{{ source('amplitude', 'event_type') }}"

