name: 'amplitude_integration_tests'
version: '0.1.0'
config-version: 2
profile: 'integration_tests'


vars:
    amplitude_schema: amplitude_source_integration_tests
    amplitude_event_identifier: "amplitude_event_data"
    # finish

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

seeds:
  amplitude_integration_tests:
    +column_types:
      _fivetran_synced: timestamp




seeds:
  snapchat_ads_source_integration_tests:
    +quote_columns: "{{ true if target.type in ('redshift', 'postgres') else false }}"
  snapchat_ads_integration_tests:
    snapchat_ad_hourly_report_data:
      +column_types:
        date: timestamp
    snapchat_creative_url_tag_history_data:
      +column_types:
        updated_at: timestamp