name: 'amplitude_integration_tests'
version: '0.1.0'
config-version: 2
profile: 'integration_tests'


vars:
  amplitude: 
    event: "{{ ref('event') }}"


seeds:
  amplitude_integration_tests:
    +column_types:
      _fivetran_synced: timestamp